---
name: "FinLibrary"
guid: "f9ee3ece-7b7e-4577-823c-4d75a0db6af5"
version: "0.1.0.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "Jellyfin Library Organizer."
description: >
  FinLibrary is a plugin for Jellyfin that helps you organize your media library.
  It checks TMDB for movie information, and renames the file accoringly,
  and folder organization based on your preferences.
  With FinLibrary,  you can keep your media library tidy and easily accessible.
category: "General"
owner: "Sleepmode"
artifacts:
- "FinLibrary.dll"
changelog: >
  Initial release.
